### ISSUE TITLE
Promise err handling

### ISSUE THREAD

**Issue by diegoaguilar** [David-Hackro/Test-Pokemon#4]
So a `Promise` object offers two properties, `resolve` and `reject`, called like that by convention from spec.

When you get an `err` you `reject(err)`, when all works good you `resolve(foo)` the promise.

* https://github.com/David-Hackro/Test-Pokemon/blob/master/test2.js#L26
* https://github.com/David-Hackro/Test-Pokemon/blob/master/test2.js#L39

**Comment by David-Hackro** [comment]
solved
